FROM node:12

RUN apt-get update && \
    apt-get install -y \
        python \
        python-dev \
        python-pip \
        python-setuptools \
        groff \
        less \
    && pip install --upgrade awscli \
    && apt-get clean

ADD questo_db_definition.json .

COPY create_dynamodb_local.sh .
RUN ["chmod", "+x", "create_dynamodb_local.sh"]
CMD ["sh", "create_dynamodb_local.sh"]
